require "mechanize"
require "csv"
require "json"
require "fileutils"

require_relative "lib/client"
require_relative "lib/hw_importer"
require_relative "lib/rm_importer"
require_relative "lib/comparer"
require_relative "lib/summarizer"