# RawExporter: the RawExporter class exports to CSV the raw output from the array of hashes collated.
#
# Giving output such as the below:
#   22913,Chelsea and Kensington 2间开阔卧室公寓,3
#   22917,Chelsea and Kensington 2间适宜卧室公寓,3
#   45717,Camden 2间舒适卧室公寓,4
#
# Usage:
#
#   RawExporter.new("tujia", "london", output).import
#
# Output is generated by the +Comparer+ class and passed to the RawExporter when instantiated.
#
# ...where output is an array of hashes like so:
# {:rm_id=>"441790", :title=>"London 3间惊艳卧室公寓", :page=>"Not Found"}, {:rm_id=>"441793", :title=>"London 2间上佳卧室公寓", :page=>"Not Found"}

class RawExporter
  attr_reader :partner_name, :city, :output

  def initialize(partner_name, city, output)
    @partner_name = partner_name
    @city = city
    @output = output
  end

  def export
    return if output.empty?
    create_dir

    CSV.open(path_filename, "w+", headers: true, headers: output.first.keys) do |csv|
      output.each do |record|
        csv << record.values
      end
    end
  end

  private

  def path_filename
    "#{path}/#{city}_raw_#{Date.today}.csv"
  end

  def path
    "results/#{partner_name}/raw"
  end

  def create_dir
    FileUtils.mkdir_p(path)
  end
end
